spring.application.name=interview-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_tracker
spring.datasource.username=postgres
spring.datasource.password=ajit123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true